sudo: false
language: python
python:
- '3.8'
install:
- pip install pygments lxml setuptools --upgrade
- git clone https://github.com/tabatkins/bikeshed.git
- pip install --editable $PWD/bikeshed
- bikeshed update
script:
- bash "./deploy.sh"
env:
  global:
  - ENCRYPTION_LABEL: "b6936e521be2"
  - COMMIT_AUTHOR_EMAIL: "plh+deploy@w3.org"
